INSERT INTO `devroadmap`.`subject` (`detailedsubject`, `field`, `title`) VALUES ('HTML, CSS, JS', 'back', '프론트 기본');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '인터넷');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', 'OS');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '언어');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '버전관리');
INSERT INTO `devroadmap`.`subject` (`detailedsubject`, `field`, `title`) VALUES ('RDBMS, NoSQL', 'back', 'DB');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', 'API');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '캐시');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '웹 보안 지식');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '테스트');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', 'CI/CD');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '개발 설계 원칙');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '아키텍처 패턴');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '검색엔진');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '메시지 브로커');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '컨테이너화 대 가상화');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', 'graphQL');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '웹서버');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('back', '확장성있는 구축');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', '인터넷');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', 'HTML');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', 'CSS');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', 'JS');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', '버전관리');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', '웹 보안 지식');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', '패키지 관리자');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', 'CSS 설계');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', 'CSS 전처리기');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', '빌드 툴');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', '프레임워크');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', 'CSS in JS');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', '타입 체커');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', '테스트');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', '서버 사이드 렌더링');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', 'graphQL');
INSERT INTO `devroadmap`.`subject` (`field`, `title`) VALUES ('front', '정적 사이드 생성기');
